<?php
/**
 * Admin page bootstrap.
 *
 * @package EaseAccess24\Accessibility
 */

namespace EaseAccess24\Accessibility;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers the wp-admin menu page and mounts the React admin app onto it.
 */
class Admin {

	/**
	 * Script/style handle for the React admin bundle.
	 */
	const ASSET_HANDLE = 'easeaccess24-admin';

	/**
	 * Admin page hook suffix, captured when the menu is registered so we only
	 * enqueue assets on our own screen.
	 *
	 * @var string
	 */
	private $hook_suffix = '';

	/**
	 * Hook into WordPress.
	 */
	public function register() {
		add_action( 'admin_menu', array( $this, 'register_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Register the top-level admin menu page.
	 */
	public function register_menu() {
		$this->hook_suffix = add_menu_page(
			__( 'EaseAccess24 Accessibility', 'easeaccess24-accessibility' ),
			__( 'EaseAccess24', 'easeaccess24-accessibility' ),
			'manage_options',
			'easeaccess24-accessibility',
			array( $this, 'render_page' ),
			'dashicons-universal-access-alt',
			80
		);
	}

	/**
	 * Print the mount point for the React app.
	 *
	 * The container is intentionally empty; React renders into it. A no-JS
	 * fallback line keeps the screen from looking broken if scripts fail.
	 */
	public function render_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}
		?>
		<div class="wrap">
			<div id="easeaccess24-admin-root">
				<noscript>
					<?php esc_html_e( 'EaseAccess24 Accessibility requires JavaScript to be enabled in your browser.', 'easeaccess24-accessibility' ); ?>
				</noscript>
			</div>
		</div>
		<?php
	}

	/**
	 * Enqueue the built React bundle and Tailwind styles on our screen only.
	 *
	 * @param string $hook_suffix Current admin page hook suffix.
	 */
	public function enqueue_assets( $hook_suffix ) {
		if ( $hook_suffix !== $this->hook_suffix ) {
			return;
		}

		$asset_file = EASEACCESS24_PATH . 'build/index.asset.php';

		// Dependencies + version come from wp-scripts' dependency extraction, so
		// React is provided by WordPress (wp-element) rather than bundled twice.
		$asset = file_exists( $asset_file )
			? require $asset_file
			: array(
				'dependencies' => array(),
				'version'      => EASEACCESS24_VERSION,
			);

		wp_enqueue_script(
			self::ASSET_HANDLE,
			EASEACCESS24_URL . 'build/index.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		// Use the RTL stylesheet (generated by wp-scripts) when the active plugin
		// language is right-to-left, so layout mirrors correctly. This keys off
		// the plugin's own language choice, not WordPress's is_rtl(), because the
		// two are independent.
		$style_file = Settings::is_rtl() ? 'build/index-rtl.css' : 'build/index.css';

		wp_enqueue_style(
			self::ASSET_HANDLE,
			EASEACCESS24_URL . $style_file,
			array(),
			$asset['version']
		);

		// Bootstrap data for the app. The nonce authenticates REST calls to the
		// easeaccess24/v1 routes; settings carries the current connection so the
		// app boots with the stored Widget Key already in hand.
		//
		// Health-check additions (Phase 04):
		// - homeUrl:          front-end target the probe iframe loads.
		// - sdkUrl:           the exact SDK URL, for the reachability check.
		// - healthCheckNonce: authorizes the front-end probe request.
		// - environment:      lets the UI stay honest on non-authorized hosts,
		// where the widget cannot render (informational, not
		// a failure).
		$key = Connection::get_widget_key();

		wp_localize_script(
			self::ASSET_HANDLE,
			'easeAccess24Data',
			array(
				'restUrl'          => esc_url_raw( rest_url() ),
				'nonce'            => wp_create_nonce( 'wp_rest' ),
				'adminUrl'         => esc_url_raw( admin_url() ),
				'homeUrl'          => esc_url_raw( home_url( '/' ) ),
				'sdkUrl'           => SdkLoader::url_for( $key ),
				'healthCheckNonce' => wp_create_nonce( HealthCheck::NONCE_ACTION ),
				'version'          => EASEACCESS24_VERSION,
				'locale'           => get_user_locale(),
				// Active UI language + the shipped translation bundles. i18next is
				// initialized from these on the JS side (src/i18n). Both launch
				// languages are injected so the dropdown switches instantly with
				// no reload; English is always present as the fallback.
				'language'         => Settings::get_language(),
				'translations'     => Settings::translations(),
				'environment'      => self::environment_flags(),
				'settings'         => Connection::get(),
				// Cache/optimizer plugins active on this site. Static per page load
				// (active plugins can't change without a reload), so it's passed as
				// bootstrap data rather than fetched over REST. Local state only —
				// no remote calls.
				'compatibility'    => Compatibility::detect(),
			)
		);
	}

	/**
	 * Detect a non-production host so the UI can explain (not fail) when the
	 * widget does not render there. Detection is best-effort and never blocks.
	 *
	 * Public + static so other modules (e.g. the Support Report) share one source
	 * of truth for environment detection.
	 *
	 * @return array<string,bool> { isLocalhost, isStaging }
	 */
	public static function environment_flags() {
		$host = (string) wp_parse_url( home_url(), PHP_URL_HOST );
		$host = strtolower( $host );

		$is_localhost = in_array( $host, array( 'localhost', '127.0.0.1', '::1' ), true )
			|| (bool) preg_match( '/\.(local|test|localhost)$/', $host );

		$env        = function_exists( 'wp_get_environment_type' ) ? wp_get_environment_type() : 'production';
		$is_staging = in_array( $env, array( 'staging', 'development' ), true )
			|| (bool) preg_match( '/(^|[.-])(staging|stage|dev)([.-]|$)/', $host );

		return array(
			'isLocalhost' => $is_localhost,
			'isStaging'   => $is_staging && ! $is_localhost,
		);
	}
}
